import { useState } from "react";
import { ArrowLeft } from "lucide-react";
import { Navbar } from "../../../components/Navbar";
import { normalizarVendaInsumos, VendaComEntradaInsumosExamesDetalhe } from "./VendaComEntradaInsumosExamesDetalhe";

const GREEN = "#1A7A3C";

export function EditarVendaComEntradaInsumosExamesPage({ dados, onLogout, onNavigate }: any) {
  const inicial = normalizarVendaInsumos(dados);
  const [salvo, setSalvo] = useState<any>(null);
  const [confirmar, setConfirmar] = useState(false);
  const [atualizado, setAtualizado] = useState(inicial);
  return <div className="min-h-screen bg-[#f2f3f5] pb-20"><Navbar onLogout={onLogout} onNavigate={onNavigate} currentScreen="venda-entrada-insumos-exames" hideSearch /><main className="max-w-5xl mx-auto px-4 md:px-6 py-6 flex flex-col gap-4"><div><button type="button" onClick={() => onNavigate("visualizar-venda-entrada-insumos-exames", inicial)} className="flex items-center gap-1 text-sm mb-3 font-semibold" style={{ color: GREEN }}><ArrowLeft size={15} /> Visualizar Venda</button><div className="flex justify-between items-center gap-4"><h1 className="text-2xl font-semibold text-gray-900">Editar Venda com Entrada de Insumos para Exames</h1><button type="button" onClick={() => setConfirmar(true)} className="px-5 h-10 bg-[#1A7A3C] text-white text-sm font-semibold rounded-md">Salvar</button></div></div><VendaComEntradaInsumosExamesDetalhe dados={inicial} mode="edit" onSalvar={setAtualizado} /></main>{confirmar && <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-[9999] p-4"><div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6 text-center"><h3 className="text-lg font-bold text-gray-900">Salvar alterações?</h3><p className="text-sm text-gray-500 mt-1">Confirme para atualizar os dados da venda.</p><div className="flex gap-3 justify-center mt-6"><button onClick={() => setConfirmar(false)} className="px-5 h-11 rounded-md border border-[#1A7A3C] text-[#1A7A3C] text-sm font-semibold">Cancelar</button><button onClick={() => { setConfirmar(false); setSalvo(atualizado); }} className="px-5 h-11 rounded-md bg-[#1A7A3C] text-white text-sm font-semibold">Salvar</button></div></div></div>}{salvo && <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-[9999] p-4"><div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6 text-center"><h3 className="text-lg font-bold text-gray-900">Alterações salvas com sucesso!</h3><div className="flex gap-3 justify-center mt-6"><button onClick={() => onNavigate("venda-entrada-insumos-exames")} className="px-5 h-11 rounded-md border border-[#1A7A3C] text-[#1A7A3C] text-sm font-semibold">Voltar</button><button onClick={() => onNavigate("visualizar-venda-entrada-insumos-exames", salvo)} className="px-5 h-11 rounded-md bg-[#1A7A3C] text-white text-sm font-semibold">Visualizar</button></div></div></div>}</div>;
}
