import { useState } from "react";
import { ArrowLeft, ChevronDown, ChevronUp, Pencil } from "lucide-react";
import { Navbar } from "../../../components/Navbar";
import { FloatInput } from "../../../components/ui/FormKit";
import { classificacaoLabel, Receita } from "./receitaData";

export function VisualizarReceitaPage({ dados, onLogout, onNavigate }: { dados: Receita; onLogout: () => void; onNavigate: (screen: any, data?: any) => void }) {
  const [open, setOpen] = useState(true);
  return <div className="min-h-screen bg-[#f2f3f5]"><Navbar onLogout={onLogout} onNavigate={onNavigate} currentScreen="receita" hideSearch /><main className="max-w-[1088px] mx-auto px-4 md:px-6 py-6 flex flex-col gap-4"><div><button type="button" onClick={() => onNavigate("receita")} className="flex items-center gap-1 text-sm mb-3 font-semibold text-[#1A7A3C]"><ArrowLeft size={15} />Todas as Receitas</button><div className="flex items-center justify-between gap-3"><h1 className="text-2xl font-semibold text-gray-900">Visualizar Receita</h1><button type="button" onClick={() => onNavigate("editar-receita", dados)} className="px-5 h-10 bg-[#1A7A3C] text-white text-xs font-bold rounded-md flex items-center gap-2"><Pencil size={15} />Editar</button></div></div><section className="bg-white rounded-xl shadow-sm overflow-visible"><button type="button" onClick={() => setOpen(!open)} className="w-full flex items-center justify-between px-6 py-4 text-left hover:bg-gray-50"><span className="text-base font-semibold text-gray-800">Informações Básicas</span>{open ? <ChevronUp size={18} className="text-gray-400" /> : <ChevronDown size={18} className="text-gray-400" />}</button>{open && <div className="px-6 pb-6 border-t border-gray-100 pt-5 grid grid-cols-1 md:grid-cols-2 gap-5"><FloatInput label="Código" value={dados.codigo} disabled onChange={() => {}} /><FloatInput label="Descrição" value={dados.descricao} disabled onChange={() => {}} /><FloatInput label="Classificação de Receita" value={classificacaoLabel(dados.classificacao)} disabled onChange={() => {}} className="md:col-span-2" /><FloatInput label="Situação" value={dados.situacao} disabled onChange={() => {}} /></div>}</section></main></div>;
}
